spring:
  datasource:
    url: "${DATABRICKS_URL}"
    driver-class-name: "com.databricks.client.jdbc.Driver"
    username: "token"
    password: "${DATABRICKS_TOKEN}"
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: "com.databricks.azure.config.DatabricksDialect"
        show_sql: true
        format_sql: true

  sql:
    init:
      mode: always
